# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20170918_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
